import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';
import Script from 'next/script';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* bg-neutral-900 */}
      <Head>
        <Script
          src="https://cdn.jsdelivr.net/npm/eruda"
          async
          // strategy="beforeInteractive"
        ></Script>
        <Script async>eruda.init();</Script>
      </Head>
      <body className={`${inter.className} text-white h-full w-dvw bg-red-100`}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
