import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import('eruda').then((eruda) => eruda.default.init());

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* bg-neutral-900 */}
      <Script src="https://cdn.jsdelivr.net/npm/eruda"></Script>
      {/* <Script>eruda.init()</Script> */}
      <body className={`${inter.className} text-white h-full w-dvw bg-red-100`}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
